### ISSUE TITLE
Edgerouter

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-registry#40] opened 2015-11-05 22:11 UTC

**Comment by onpaws** [comment] 2017-02-27 04:03
(Writing here in hopes this is the right place to start a dialogue on developing an Edgerouter appliance - mods, if there's a better place please point me in the right direction.)

I've been looking into what it will take to build an "EdgeMAX/EdgeOS" appliance and thought I'd share some preliminary findings.

Given the [fork](https://community.ubnt.com/t5/EdgeMAX/Relation-between-EdgeOS-and-Vyatta-VyOS/td-p/1721360) it's unsurprising that a config from the latest EdgeOS (1.9.1 at time of writing) is likely to fail when dropped into the official [VyOS appliance](https://gns3.com/marketplace/appliance/vyos) (1.2.0-beta1). 
It appears EdgeOS 1.8+ [diverges](https://www.reddit.com/r/Ubiquiti/comments/3rh0fi/edgeos_gns3/) enough from VyOS to break config compat. (I tried. [1](https://gist.github.com/onpaws/89f3b0e34b3a352db6e4167e851364d8), [2](https://www.reddit.com/r/Ubiquiti/comments/52sdki/is_it_safe_to_edit_configboot_and_try_put_it_back/
), [image](http://dl.ubnt.com/firmwares/edgemax/v1.9.1/ER-e200.v1.9.1.4939098.tar).)

I see the existing VyOS [appliance definition](https://github.com/GNS3/gns3-registry/blob/master/appliances/vyos.gns3a#L27) uses an amd64 ISO on Qemu.
Whereas the latest EdgeOS [image](http://dl.ubnt.com/firmwares/edgemax/v1.9.1/ER-e200.v1.9.1.4939098.tar) appears to be a MIPS Linux kernel.

Would love to see if Dynamips could be a viable way to run EdgeOS. Am I on the right track here?
Is there any previous work on this I could review?

Cheers!

**Comment by noplay** [comment] 2017-02-27 08:13
I'm not sure qemu can load this without rebuilding a disk image around it.

I try this:
qemu-system-mips64 -kernel vmlinux.tmp -initrd squashfs.tmp

But without luck

**Comment by onpaws** [comment] 2017-02-27 09:07
Thanks for the quick answer. 
By 'disk image around it' do you mean an ISO?

**Comment by noplay** [comment] 2017-02-27 09:37
From my understanding the squashfs.tmp is the image of a filesystem, but not ready to be use directly by qemu.

If you are an edge customer did you try to contact the support? Some manufacturers have internal images for tests and sometimes when a customer ask them they open the stuff.

**Comment by onpaws** [comment] 2017-02-27 16:37
Interesting idea to contact support, thanks will try!

**Comment by noplay** [comment] 2017-02-27 17:59
I hope for good news. As I say some manufacturers publish images after a
customer contacted the support. I know many manufacturers using GNS3
without publishing images because it's not a priority.

**Comment by onpaws** [comment] 2017-02-27 21:42
I [posted](https://community.ubnt.com/t5/EdgeMAX-Feature-Requests/Request-Simulator-software-for-Ubiquiti-EdgeRouter-and-Ubiquiti/idc-p/1849259#M2053) at Ubiquiti forums. While we wait for a reply, here are some additional findings.

The EdgeRouter line ([example](https://wikidevi.com/wiki/Ubiquiti_Networks_EdgeRouter_POE)) uses the Cavium [Octeon](https://cavium.com/pdfFiles/CN50XX_PB_Rev1.pdf)[1], a MIPS64-based chipset that  offloads crypto, TCP, QoS and other things.

At their [community site](http://cnusers.org) (registration required) Cavium apparently offers an SDK that includes an emulator, according to [this](https://wiki.freebsd.org/FreeBSD/mips/OcteonSim).

I may have found kernel [boot args](https://wiki.openwrt.org/toh/ubiquiti/edgerouter.lite)
```
874120 bytes read
argv[2]: coremask=0x3
argv[3]: root=/dev/sda2
argv[4]: rootdelay=15
argv[5]: rw
argv[6]: rootsqimg=squashfs.img
argv[7]: rootsqwdir=w
argv[8]: mtdparts=phys_mapped_flash:512k(boot0),512k(boot1),64k@3072k(eeprom)
```
Still need to see if Qemu can handle this image.

[1] Confirmed by this [job post](http://ubnt.theresumator.com/apply/Zwx0zN/Firmware-Engineer).

**Comment by onpaws** [comment] 2017-02-27 22:51
Ubiquiti support shared [this](https://community.ubnt.com/t5/EdgeMAX/Firmware-Simulator/td-p/551110).

In hopes of getting somewhere I additionally commented on other threads where others were also requesting to accomplish this.

**Comment by noplay** [comment] 2017-02-28 10:10
So it's seem they put security preventing you to run it :(

**Comment by onpaws** [comment] 2017-02-28 15:27
I saw dmbaturin's message on that too.
I'm going to try anyway until I get stuck/it's beyond my skills.

**Comment by onpaws** [comment] 2017-03-02 17:27
Running dmesg on my EdgeRouter, which appears to have `500MHz CN5020 Octeon Plus - Dual Core - SCP Version, I Temp` SOC:


`Linux version 3.10.20-UBNT (root@ubnt-builder2) (gcc version 4.7.0 (Cavium Inc. Version: SDK_3_1_0_p2 build 34) ) #1 SMP
 Fri Dec 2 02:30:08 PST 2016`

Option 1) leverage the Octeon emulator from SDK
Option 2) use Qemu. In this case it seems it comes down to whether the Linux kernel in the EdgeRouter image will fallback to software for custom hardware e.g. the checksum offload & crypto

**Comment by onpaws** [comment] 2017-03-03 18:03
Based on this [comment](https://www.reddit.com/r/Ubiquiti/comments/3rh0fi/edgeos_gns3/) I thought EdgeOS 1.8+ was the version to diverge, but according to [this](https://lg.io/2015/01/11/the-ubiquiti-edgerouter-configuring-this-extremely-lowcost-enterprisegrade-router-for-home-use.html) (see "Port forwarding"), 1.4 already diverged enough to break common features.

Just means this problem has been around for more years than I thought.

**Comment by onpaws** [comment] 2017-03-07 19:52
I was able to get qemu-system-mips64 to boot a Debian wheezy MIPS64 kernel image. 

Since I wasn't able to get qemu to boot Ubiquiti kernel directly now investigating how to run kernel via U-Boot. (That's how the physical devices are set up.)

**Comment by noplay** [comment] 2017-03-08 08:12
Good to know

**Comment by onpaws** [comment] 2017-04-05 19:21
I finally received account approval at Cavium community site.
Will experiment more this weekend.

**Comment by onpaws** [comment] 2018-06-11 10:46
As you might have guessed by now, I haven't looked into this for a while because it is no longer as pressing for my circumstances.

That said, for anyone inclined I do see folks posting on the Ubiquiti forums every now and then expressing a desire for precisely this. Hopefully one day!

**Comment by adosztal** [comment] 2019-04-21 18:28
I see a couple of requests but Ubiquity haven't provided a VM so far. I suggest to close this issue and either open a new one or have this one re-opened if they release something.

**Closed** 2019-04-22 06:12 UTC
Labels: appliance
